import json
from typing import TypedDict, Any, Dict, Annotated
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, AIMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langchain_core.tools import tool
from langgraph.prebuilt import ToolNode
import os

load_dotenv()
api_key=os.getenv("GOOGLE_API_KEY")

# We will use Gemini as a stand-in for the various models (Sonnet, Haiku, FRT).
llm_orchestrator = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", temperature=0,api_key=api_key) # Acting as "Sonnet"
llm_haiku = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", temperature=0.5,api_key=api_key)      # Acting as "Haiku"
llm_frt = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", temperature=0.1,api_key=api_key)        # Acting as "FRT"


# 1. Define the Global State matching the diagram
class OrchestratorState(TypedDict):
    messages: Annotated[list, add_messages] #Messages to support tool calling loop
    user_json: Dict[str, Any]      # Initial input from the user (JSON)
    available_tools: list[str]     # List of tool descriptions available to the orchestrator
    sql_query: str                 # Query generated by the Orchestrator
    db_result_mixed: Dict[str, Any]# Output from the DB (Data + JSON meta)
    processed_data: str            # Cleaned/Sanitized Data payload
    haiku_analysis: str            # Output from the Haiku Sub-Agent
    frt_xml: str                   # Output from the FRT Sub-Agent (XML format)


# 2. Define MCP Tools (Mocked for Orchestrator to use)
@tool
def mcp_lookup_table_schema(table_name: str) -> str:
    """An MCP tool to look up table schemas. Call this FIRST if you don't know the table schema."""
    print(f"\n   [Tool Execution] -> User called mcp_lookup_table_schema for '{table_name}'")
    # Mocking an MCP tool response
    if table_name.lower() in ["sales", "sales_data"]:
        return "Schema for sales: id INT, region VARCHAR, quarter VARCHAR, total_amount FLOAT"
    return f"Schema for {table_name}: id INT, name VARCHAR, value FLOAT"

tools = [mcp_lookup_table_schema]
orchestrator_with_tools = llm_orchestrator.bind_tools(tools)


# 3. Define the Nodes
def orchestrator_node(state: OrchestratorState) -> Dict[str, Any]:
    """Orchestrator / Sonnet
    Takes the JSON input, uses tools/logic to understand it, and generates a SQL query.
    Runs in a loop with ToolNode if a tool call is needed.
    """
    user_req = state.get("user_json", {})
    available_tools = state.get("available_tools", [])
    messages = state.get("messages", [])
    
    is_first_run = not messages
    if is_first_run:
        # Format the tools for the prompt
        tools_prompt = ""
        if available_tools:
            tools_prompt = "\n    AVAILABLE TOOLS:\n"
            for tool_desc in available_tools:
                tools_prompt += f"    - {tool_desc}\n"
        
        prompt = f"""
            You are the central Orchestrator Agent. Your primary objective is to translate user intent into precise, executable SQL queries.

            CRITICAL INSTRUCTIONS:
            1. UNDERSTAND: Carefully analyze the provided User JSON Request to determine the core data needed.
            2. EXPLORE: If you do not know the exact schema, use your available tools to look up the correct table and column names before writing the query.{tools_prompt}
            3. GENERATE: Construct a valid SQLite query to fulfill the request. 
            4. FORMAT: Return ONLY the raw SQL query string inside your response. Do not include markdown formatting (like ```sql), do not include explanations, and do not include conversational text.
            If you call a tool, I will reply with the tool result. Once you have enough info, output the SQL query.

            User JSON Request: {json.dumps(user_req)}
            """
        initial_msg = HumanMessage(content=prompt)
        input_messages = [initial_msg]
    else:
        input_messages = messages
        
    response = orchestrator_with_tools.invoke(input_messages)
    
    messages_to_return = [initial_msg, response] if is_first_run else [response]
    
    # Check if a tool was called
    if hasattr(response, "tool_calls") and response.tool_calls:
        # Still exploring, return updated messages to route to ToolNode
        return {"messages": messages_to_return}
    else:
        # Finished exploring, extract the final query
        content_val = response.content
        if isinstance(content_val, list):
            content_val = "".join([m.get("text", "") if isinstance(m, dict) else str(m) for m in content_val])
        else:
            content_val = str(content_val)
        query = content_val.replace("```sql", "").replace("```", "").strip()
        return {"sql_query": query, "messages": messages_to_return}



def should_continue(state: OrchestratorState) -> str:
    """Conditional edge router from Orchestrator"""
    messages = state.get("messages", [])
    last_message = messages[-1]
    # If the LLM made a tool call, we must go to 'tools'
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    # Otherwise, we proceed to SQL execution
    return "SQL_DB"

def sql_db_node(state: OrchestratorState) -> OrchestratorState:
    """
    SQL DB execution node.
    Executes the query and returns a mixed 'Data + JSON' payload.
    """
    query = state.get("sql_query", "")
    print(f"Executing SQL: {query}")
    
    # Mocking executing a query against a DB
    mock_db_result = {
        "metadata_json": {"query_time": "0.01s", "rows_returned": 2},
        "raw_data": [
            {"id": 1, "region": "US", "quarter": "Q3", "total_amount": 10500.00},
            {"id": 2, "region": "US", "quarter": "Q3", "total_amount": 20400.00}
        ]
    }
    
    return {"db_result_mixed": mock_db_result}

def data_processor_node(state: OrchestratorState) -> OrchestratorState:
    """
    Data + JSON -> Data 
    Extracts purely the data ready for the sub-agents.
    """
    mixed_data = state.get("db_result_mixed", {})
    # Extract only the data, discarding the JSON metadata
    pure_data = mixed_data.get("raw_data", [])
    
    # Convert to a string payload for the LLMs
    return {"processed_data": json.dumps(pure_data)}

def haiku_node(state: OrchestratorState) -> OrchestratorState:
    """
    Haiku Sub-Agent.
    Performs quick analysis on the Data.
    """
    data = state.get("processed_data", "")
    
    prompt = f"""
    You are the Haiku Sub-Agent, a specialized data analyst. 
    Review the following raw data extracted from the application's database:
    {data}
    
    Your task is to provide a brief, high-level analytical summary of this data.
    - Identify key trends, totals, or anomalies.
    - Keep your response structured, concise, and business-focused.
    - Do not output code; only provide natural language insights.
    """
    response = llm_haiku.invoke([HumanMessage(content=prompt)])
    
    content_val = response.content
    if isinstance(content_val, list):
        content_val = "".join([m.get("text", "") if isinstance(m, dict) else str(m) for m in content_val])
    else:
        content_val = str(content_val)
        
    return {"haiku_analysis": content_val}

def frt_node(state: OrchestratorState) -> OrchestratorState:
    """
    FRT Sub-Agent.
    Takes the Data and formats it strictly as XML to return to the user.
    """
    data = state.get("processed_data", "")
    
    prompt = f"""
    You are the FRT (Format Rendering Tool) Sub-Agent. 
    Your strict objective is to convert raw application data into well-formed, valid XML.
    
    Data payload to convert:
    {data}
    
    CRITICAL INSTRUCTIONS:
    1. Structure the output with a root element `<response>` and wrap each data item in a nested `<item>` container.
    2. Convert dictionary keys into XML tags and dictionary values into text nodes.
    3. Return ONLY the raw XML string. Do not include markdown code block syntax (like ```xml), do not include any preamble, and do not include any conversational text. 
    """
    response = llm_frt.invoke([HumanMessage(content=prompt)])
    
    content_val = response.content
    if isinstance(content_val, list):
        content_val = "".join([m.get("text", "") if isinstance(m, dict) else str(m) for m in content_val])
    else:
        content_val = str(content_val)
        
    xml_output = content_val.replace("```xml", "").replace("```", "").strip()
    
    return {"frt_xml": xml_output}

# 4. Building the Connections Graph
graph = StateGraph(OrchestratorState)

# Add Nodes
graph.add_node("Orchestrator", orchestrator_node)
# Add the ToolNode which executes the actual Python tools
tool_node = ToolNode(tools=[mcp_lookup_table_schema])
graph.add_node("tools", tool_node)

graph.add_node("SQL_DB", sql_db_node)
graph.add_node("Data_Processor", data_processor_node)
graph.add_node("Haiku_Agent", haiku_node)
graph.add_node("FRT_Agent", frt_node)

# Add Edges spanning the flowchart
graph.add_edge(START, "Orchestrator")        # User JSON -> Orchestrator

# Conditional Edge: Either loop to tools, or proceed to SQL_DB
graph.add_conditional_edges("Orchestrator", should_continue)
# Loop Edge: After tool execution, go back to the orchestrator to reason
graph.add_edge("tools", "Orchestrator")      

graph.add_edge("SQL_DB", "Data_Processor")   # SQL DB -> Data + JSON 
graph.add_edge("Data_Processor", "Haiku_Agent") # Data -> Haiku
graph.add_edge("Data_Processor", "FRT_Agent")   # Data -> FRT
graph.add_edge("Haiku_Agent", END)
graph.add_edge("FRT_Agent", END)             # FRT XML -> User

# Compile
app = graph.compile()


# 5. Testing the Orchestration Flow
if __name__ == "__main__":
    print("--- Starting Orchestration Flow ---")
    
    # 1. User inputs JSON
    initial_user_input = {
        "intent": "Get total sales figures",
        "parameters": {"region": "US", "quarter": "Q3"}
    }
    
    initial_state = {
        "messages": [],
        "user_json": initial_user_input,
        "available_tools": [
            "mcp_lookup_table_schema(table_name: str) -> str: Use this tool to look up table schemas if you don't know the columns. Call this FIRST if you need to construct a query."
        ]
    }
    
    print("\n[User Input] (JSON):")
    print(json.dumps(initial_user_input, indent=2))
    
    # 2. Run the Graph
    print("\n--- Executing Graph Nodes ---")
    try:
        final_state = app.invoke(initial_state)
        
        # 3. Retrieve and display the final outputs of the Sub-Agents
        print("\n\n--- Final Outputs ---")
        print(f"\n[Generated Query]:\n{final_state.get('sql_query')}")
        print(f"\n[Haiku Sub-Agent Analysis]:\n{final_state.get('haiku_analysis')}")
        print(f"\n[FRT Sub-Agent Output] (XML sent to User):\n{final_state.get('frt_xml')}")
        
    except BaseException as e:
        if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e):
            print("\n❌ API Rate Limit Reached (429 RESOURCE_EXHAUSTED).")
            print("The orchestration logic is correct, but your LLM API quota is currently maxed out.")
            print("Please wait a minute and run the script again.")
        else:
            print(f"\nAn error occurred during execution: {e}")
