"""
Tool: execute_sql_query
Executes a read-only SELECT query via the mcp_server DatabaseClient (SQLAlchemy),
extracts the data, and returns a combined JSON payload containing both
the data records and the chart attributes for the downstream charting agent.
"""

import json
import re
from functools import lru_cache
from typing import Any, Dict, Optional

from mcp_server.config import ServerSettings
from mcp_server.database import DatabaseClient, QueryValidationError


# Known table name typo corrections (LLMs often drop trailing 's' on plurals)
TABLE_NAME_ALIASES: Dict[str, str] = {
    "channel_metric": "channel_metrics",
    "input_type_metric": "input_type_metrics",
    "language_statistic": "language_statistics",
    "output_type_statistic": "output_type_statistics",
    "video_list": "video_list_data",
    "monthly_count_duration": "monthly_counts_duration",
    "monthly_count": "monthly_counts_duration",
}


@lru_cache(maxsize=1)
def _get_db() -> DatabaseClient:
    """Return a shared DatabaseClient instance (created once per process)."""
    settings = ServerSettings.from_env()
    return DatabaseClient(
        database_url=settings.database_url,
        default_schema=settings.default_schema,
    )


def execute_sql_query(query: str, chart_attributes: Optional[Dict[str, Any]] = None) -> str:
    """
    Execute a SELECT SQL query via the MCP server DatabaseClient and bundle
    the results with chart attributes.

    Args:
        query:            A valid PostgreSQL SELECT statement.
        chart_attributes: A dictionary of chart settings generated by the
                          orchestrator (e.g., {"type": "bar", "x_axis": "month",
                          "y_axis": "revenue", "title": "Monthly Revenue"}).

    Returns:
        A JSON string containing a dict with 'data' and 'chart_attributes' keys,
        or an error JSON payload on failure.
    """
    if chart_attributes is None:
        chart_attributes = {}

    # Strip markdown code fences the LLM sometimes wraps around the SQL
    query = query.strip().strip("```sql").strip("```").strip()

    # Auto-correct known LLM table name typos (e.g. 'channel_metric' -> 'channel_metrics')
    for wrong, correct in TABLE_NAME_ALIASES.items():
        query = re.sub(rf"\b{re.escape(wrong)}\b", correct, query, flags=re.IGNORECASE)

    try:
        db = _get_db()
        # DatabaseClient.run_read_only_query handles read-only validation internally
        df = db.run_read_only_query(query, limit=5000)
        df = df.fillna(0)

        payload = {
            "data": df.to_dict(orient="records"),
            "chart_attributes": chart_attributes,
        }
        return json.dumps(payload, default=str)

    except QueryValidationError as exc:
        return json.dumps({"error": f"Query validation error: {exc}"})
    except Exception as exc:
        return json.dumps({"error": f"SQL Execution Error: {exc}"})