"""
Tool: execute_sql_query
Executes a read-only SELECT query via the shared MCP DatabaseClient,
extracts the data, and returns a combined JSON payload containing both
the data records and the chart attributes for the downstream charting agent.
"""

import json
import re
from typing import Any, Dict, Optional

from tools._db import get_db, DEFAULT_QUERY_LIMIT, MAX_QUERY_LIMIT
from mcp_server.database import QueryValidationError


def execute_sql_query(query: str, chart_attributes: Optional[Dict[str, Any]] = None) -> str:
    """
    Execute a SELECT SQL query and bundle the results with chart attributes.

    Routes through the MCP DatabaseClient which provides:
      - Query validation (blocks mutations, multi-statement)
      - Proper LIMIT enforcement
      - Clean connection management

    Args:
        query:            A valid SELECT statement.
        chart_attributes: A dictionary of chart settings generated by the
                          orchestrator (e.g., {"type": "bar", "x_axis": "month",
                          "y_axis": "revenue", "title": "Monthly Revenue"}).

    Returns:
        A JSON string containing a dict with 'data' and 'chart_attributes' keys,
        or an error JSON payload on failure.
    """
    if chart_attributes is None:
        chart_attributes = {}

    # Strip markdown code fences the LLM sometimes wraps around the SQL.
    # NOTE: must use regex, NOT str.strip() — strip() removes individual
    # characters, which would corrupt table names (e.g. raw_videos → raw_video).
    query = query.strip()
    query = re.sub(r"^```(?:sql)?\s*\n?", "", query, flags=re.IGNORECASE)
    query = re.sub(r"\n?```\s*$", "", query).strip()

    try:
        db = get_db()
        limit = min(DEFAULT_QUERY_LIMIT, MAX_QUERY_LIMIT)
        df = db.run_read_only_query(query, limit=limit)

        df = df.fillna(0)

        payload = {
            "data": df.to_dict(orient="records"),
            "chart_attributes": chart_attributes,
        }
        return json.dumps(payload, default=str)  # default=str handles dates/Decimals

    except QueryValidationError as exc:
        return json.dumps({"error": str(exc)})
    except Exception as exc:
        return json.dumps({"error": f"SQL Execution Error: {exc}"})