import json
from typing import TypedDict, Any, Dict
from logger_setup import get_logger

logger = get_logger(__name__)

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langgraph.graph import StateGraph, START, END
from langchain_core.tools import tool

load_dotenv()

# We will use Gemini as a stand-in for the various models (Sonnet, Haiku, FRT). 
# You can replace the model strings later with actual Anthropic models if needed.
llm_orchestrator = HuggingFaceEndpoint(repo_id="Qwen/Qwen3.5-35B-A3B") # Acting as "Sonnet"
llm_haiku = HuggingFaceEndpoint(repo_id="Qwen/Qwen3.5-35B-A3B")      # Acting as "Haiku"
llm_frt = HuggingFaceEndpoint(repo_id="Qwen/Qwen3.5-35B-A3B")        # Acting as "FRT"

model = ChatHuggingFace(llm=llm_orchestrator)
model_haiku = ChatHuggingFace(llm=llm_haiku)
model_frt = ChatHuggingFace(llm=llm_frt)

# 1. Define the Global State matching the diagram
class OrchestratorState(TypedDict):
    user_json: Dict[str, Any]      # Initial input from the user (JSON)
    sql_query: str                 # Query generated by the Orchestrator
    db_result_mixed: Dict[str, Any]# Output from the DB (Data + JSON meta)
    processed_data: str            # Cleaned/Sanitized Data payload
    haiku_analysis: str            # Output from the Haiku Sub-Agent
    frt_xml: str                   # Output from the FRT Sub-Agent (XML format)


# 2. Define MCP Tools (Mocked for Orchestrator to use)
@tool
def mcp_lookup_table_schema(table_name: str) -> str:
    """An MCP tool to look up table schemas."""
    # Mocking an MCP tool response
    return f"Schema for {table_name}: id INT, name VARCHAR, value FLOAT"

tools = [mcp_lookup_table_schema]
orchestrator_with_tools = model.bind_tools(tools)


# 3. Define the Nodes
def orchestrator_node(state: OrchestratorState) -> OrchestratorState:
    """
    Orchestrator / Sonnet
    Takes the JSON input, uses tools/logic to understand it, and generates a SQL query.
    """
    user_req = state.get("user_json", {})
    
    prompt = f"""
    You are the central Orchestrator Agent. Your primary objective is to translate user intent into precise, executable SQL queries.
    
    CRITICAL INSTRUCTIONS:
    1. UNDERSTAND: Carefully analyze the provided User JSON Request to determine the core data needed.
    2. EXPLORE: If you do not know the exact schema, use your available tools (e.g., `mcp_lookup_table_schema`) to look up the correct table and column names before writing the query.
    3. GENERATE: Construct a valid SQLite query to fulfill the request.Ensure proper table and column names are used. 
    4. FORMAT: Return ONLY the raw SQL query string inside your response. Do not include markdown formatting (like ```sql), do not include explanations, and do not include conversational text.
    
    User JSON Request: {json.dumps(user_req)}
    """
    
    response = orchestrator_with_tools.invoke([HumanMessage(content=prompt)])
    # In a real tool-use flow, you would handle tool messages here. 
    # For this architecture diagram, we assume it outputs the query directly.
    query = response.content.replace("```sql", "").replace("```", "").strip()
    return {"sql_query": query}


def sql_db_node(state: OrchestratorState) -> OrchestratorState:
    """
    SQL DB execution node.
    Executes the query and returns a mixed 'Data + JSON' payload.
    """
    query = state.get("sql_query", "")
    logger.info(f"Executing SQL: {query}")
    
    # Mocking executing a query against a DB
    mock_db_result = {
        "metadata_json": {"query_time": "0.01s", "rows_returned": 2},
        "raw_data": [
            {"id": 1, "name": "Item A", "value": 100},
            {"id": 2, "name": "Item B", "value": 200}
        ]
    }
    
    return {"db_result_mixed": mock_db_result}


def data_processor_node(state: OrchestratorState) -> OrchestratorState:
    """
    Data + JSON -> Data 
    Extracts purely the data ready for the sub-agents.
    """
    mixed_data = state.get("db_result_mixed", {})
    # Extract only the data, discarding the JSON metadata
    pure_data = mixed_data.get("raw_data", [])
    
    # Convert to a string payload for the LLMs
    return {"processed_data": json.dumps(pure_data)}


def haiku_node(state: OrchestratorState) -> OrchestratorState:
    """
    Haiku Sub-Agent.
    Performs quick analysis on the Data.
    """
    data = state.get("processed_data", "")
    
    prompt = f"""
    You are the Haiku Sub-Agent, a specialized data analyst. 
    Review the following raw data extracted from the application's database:
    {data}
    
    Your task is to provide a brief, high-level analytical summary of this data.
    - Identify key trends, totals, or anomalies.
    - Keep your response structured, concise, and business-focused.
    - Do not output code; only provide natural language insights.
    """
    response = model_haiku.invoke([HumanMessage(content=prompt)])
    
    return {"haiku_analysis": response.content}


def frt_node(state: OrchestratorState) -> OrchestratorState:
    """
    FRT Sub-Agent.
    Takes the Data and formats it strictly as XML to return to the user.
    """
    data = state.get("processed_data", "")
    
    prompt = f"""
    You are the FRT (Format Rendering Tool) Sub-Agent. 
    Your strict objective is to convert raw application data into well-formed, valid XML.
    
    Data payload to convert:
    {data}
    
    CRITICAL INSTRUCTIONS:
    1. Structure the output with a root element `<response>` and wrap each data item in a nested `<item>` container.
    2. Convert dictionary keys into XML tags and dictionary values into text nodes.
    3. Return ONLY the raw XML string. Do not include markdown code block syntax (like ```xml), do not include any preamble, and do not include any conversational text. 
    """
    response = model_frt.invoke([HumanMessage(content=prompt)])
    xml_output = response.content.replace("```xml", "").replace("```", "").strip()
    
    return {"frt_xml": xml_output}


# 4. Building the Connections Graph
graph = StateGraph(OrchestratorState)

# Add Nodes
graph.add_node("Orchestrator", orchestrator_node)
graph.add_node("SQL_DB", sql_db_node)
graph.add_node("Data_Processor", data_processor_node)
graph.add_node("Haiku_Agent", haiku_node)
graph.add_node("FRT_Agent", frt_node)

# Add Edges spanning the flowchart
graph.add_edge(START, "Orchestrator")        # User JSON -> Orchestrator
graph.add_edge("Orchestrator", "SQL_DB")     # Orchestrator -> SQL DB
graph.add_edge("SQL_DB", "Data_Processor")   # SQL DB -> Data + JSON 
graph.add_edge("Data_Processor", "Haiku_Agent") # Data -> Haiku
graph.add_edge("Data_Processor", "FRT_Agent")   # Data -> FRT
graph.add_edge("Haiku_Agent", END)
graph.add_edge("FRT_Agent", END)             # FRT XML -> User

# Compile
app = graph.compile()


# 5. Testing the Orchestration Flow
if __name__ == "__main__":
    logger.info("--- Starting Orchestration Flow ---")
    
    # 1. User inputs JSON
    initial_user_input = {
        "intent": "Get total sales figures",
        "parameters": {"region": "US", "quarter": "Q3"}
    }
    
    initial_state = {"user_json": initial_user_input}
    
    logger.info("[User Input] (JSON):")
    logger.info(json.dumps(initial_user_input, indent=2))
    
    # 2. Run the Graph
    logger.info("--- Executing Graph Nodes ---")
    try:
        for output in app.stream(initial_state):
            for node_name, state_snapshot in output.items():
                logger.info(f"Completed Node: {node_name}")
                
                # Print significant outputs from nodes depending on what they did
                if "sql_query" in state_snapshot and node_name == "Orchestrator":
                    logger.info(f"Generated Query: {state_snapshot['sql_query']}")
                elif "db_result_mixed" in state_snapshot and node_name == "SQL_DB":
                     logger.info(f"DB Mixed Output (Data + JSON): {state_snapshot['db_result_mixed']}")
                elif "processed_data" in state_snapshot and node_name == "Data_Processor":
                     logger.info(f"Extracted Pure Data: {state_snapshot['processed_data']}")

        
        # 3. Retrieve and display the final outputs of the Sub-Agents
        final_state = app.invoke(initial_state)
        
        logger.info("--- Final Outputs ---")
        logger.info(f"[Haiku Sub-Agent Analysis]:\n{final_state.get('haiku_analysis')}")
        logger.info(f"[FRT Sub-Agent Output] (XML sent to User):\n{final_state.get('frt_xml')}")
        
    except BaseException as e:
        if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e):
            logger.error("API Rate Limit Reached (429 RESOURCE_EXHAUSTED).")
            logger.error("The orchestration logic is correct, but your LLM API quota is currently maxed out.")
            logger.error("Please wait a minute and run the script again.")
        else:
            logger.error(f"An error occurred during execution: {e}")
