"""Pydantic models for the multi-agent analytics pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


# ── Request / Response contracts ──────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Incoming query from the frontend/backend proxy."""

    query: str
    conversation_id: str
    mode: Literal["fast", "deep", "auto"] = "auto"


class ChartAxis(BaseModel):
    field: str
    label: str
    type: str = "string"


class ChartSeries(BaseModel):
    name: str
    field: str
    color: str = "#6366f1"


class ChartSpec(BaseModel):
    """Frontend-consumable chart specification (no images)."""

    chart_type: str
    title: str
    x_axis: dict
    y_axis: dict
    series: list[dict]
    data: list[dict]
    show_legend: bool = True
    annotations: list[dict] = Field(default_factory=list)


class InsightResponse(BaseModel):
    """Final response returned to the frontend."""

    summary: str
    insights: list[str] = Field(default_factory=list)
    data_table: Optional[dict] = None
    charts: Optional[list[ChartSpec]] = None
    has_charts: bool = False
    confidence: Literal["HIGH", "MEDIUM", "LOW"] = "HIGH"
    query_used: Optional[str] = None
    execution_ms: int = 0
    path_used: Literal["fast", "deep"] = "fast"
    warnings: list[str] = Field(default_factory=list)


# ── Internal pipeline models ─────────────────────────────────────────────────

class RoutingDecision(BaseModel):
    """Output of the RouterAgent."""

    intent: str  # SIMPLE_LOOKUP | AGGREGATION | FILTER | RANK | TREND | ANALYTICS | ANOMALY | FORECAST | SCHEMA_QUERY
    complexity: Literal["LOW", "MEDIUM", "HIGH"]
    requires_chart: bool
    chart_types: list[str] = Field(default_factory=list)
    relevant_tables: list[str] = Field(default_factory=list)
    time_range_detected: bool = False
    forced_path: Literal["fast", "deep"] = "fast"
    reasoning: str = ""


class SQLResult(BaseModel):
    """Result of a validated SQL execution."""

    sql: str
    columns: list[str]
    rows: list[list]
    row_count: int
    execution_ms: int = 0
    attempts: int = 1

    def rows_as_dicts(self) -> list[dict]:
        return [dict(zip(self.columns, row)) for row in self.rows]


@dataclass
class ValidationResult:
    """Output of the 6-layer SQL validator."""

    valid: bool
    error: Optional[str] = None
    fixed_sql: Optional[str] = None
    warnings: list[str] = field(default_factory=list)


@dataclass
class QueryResult:
    """Raw result from DatabaseTool.execute()."""

    columns: list[str]
    rows: list[list]
    row_count: int
    execution_ms: int = 0


class AnalyticsStepPlan(BaseModel):
    """A single step inside an analytics execution plan."""

    step: int
    description: str
    sql_needed: bool = True


class AnalyticsPlan(BaseModel):
    """Execution plan generated by the AnalyticsAgent planner."""

    steps: list[AnalyticsStepPlan] = Field(default_factory=list)
    parallel_steps: list[int] = Field(default_factory=list)


@dataclass
class AnalyticsResult:
    """Aggregated result from the AnalyticsAgent."""

    primary_result: SQLResult
    datasets: list[dict] = field(default_factory=list)
    computed_metrics: dict = field(default_factory=dict)
    plan: Optional[AnalyticsPlan] = None


# ── Error model ───────────────────────────────────────────────────────────────

class AgentError(Exception):
    """Structured agent error with user-facing message."""

    def __init__(
        self,
        message: str,
        agent: str,
        recoverable: bool = True,
        user_message: str = "Something went wrong. Please try again.",
    ):
        super().__init__(message)
        self.agent = agent
        self.recoverable = recoverable
        self.user_message = user_message
